# Generated by Django 5.1.1 on 2025-12-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='details',
            new_name='address',
        ),
    ]
