# Generated by Django 5.1.1 on 2025-12-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('organizer', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='initiatives/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
